FROM python:3.11-slim
WORKDIR /ml
COPY ml/trainer/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY ml/trainer/ trainer/
COPY ml/data/ data/
CMD ["python", "trainer/train.py", "--device", "cpu", "--amp", "off", "--num-workers", "2"]
