server:
  port: 8083

spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

info:
  app:
    name: multiply-service
    version: 1.0.0
